# Generated by Django 5.0.6 on 2024-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_sell_buy"),
    ]

    operations = [
        migrations.AddField(
            model_name="sell_buy",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
