# Generated by Django 5.0.6 on 2024-05-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_sell_buy_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell_buy",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sells",
                to="shop.allproduct",
            ),
        ),
    ]
