# Generated by Django 4.2.2 on 2024-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_allproduct_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
