# Generated by Django 5.0.6 on 2024-05-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_sell_buy_quantity"),
        ("shop", "0006_delete_course"),
    ]

    operations = []
