# Generated by Django 4.2.2 on 2024-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
    ]
