# Generated by Django 5.0.6 on 2024-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_sell_buy_sell_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell_buy",
            name="sell_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
