# Generated by Django 4.2.2 on 2024-05-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allproduct",
            name="product_statustype",
        ),
        migrations.AddField(
            model_name="allproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.category",
            ),
        ),
    ]
